### PR TITLE
Restructure modules to make it packageable

### PR DESCRIPTION
**Pull request by akbargumbira**
Hi @timlinux @ismailsunni, after installing this parameters in safe, it should be imported this way: from parameters import x. What do you think?

### CODE REVIEW

**Comment by Gustry** [comment]
I'm not against this, I don't have a strong opinion, but I'm just thinking that `parameter` might be used by others plugins. So if both plugins are installed, you might run into conflicts.

My 2 cents

**Comment by ismailsunni** [comment]
Yes, the same things I discussed with @akbargumbira in the gitter. Can we install it in a speicific directory? So that we can add namespace / folder to point to the parameter (or the other libs).

**Comment by akbargumbira** [comment]
Listing safe_extras packages and how they are used in safe package, it's apparently quite inconsistent:

* raven used only in safe/common/custom_logging.py:
```
from raven.handlers.logging import SentryHandler
```

* pydispatcher:
```
from safe_extras.pydispatch import dispatcher
```

* simplejson used by raven imported this way:
```
import simplejson as json
```

* parameters impoted this way:
```
from safe_extras.parameters.select_parameter import SelectParameter
```

IMO, we need to make this importing style consistent first.

There are 2 possible conflicts that I could think of:
1. If other developers use this parameters package in their plugin. It depends on how they package and import it in their plugins. We add safe_extras to the system path, so if they package it under some other folder e.g ```ext_libs``` and they import it by ```ext_libs.parameters```, I guess we won't have problem.

2. If other developers use other parameters package (http://parameters.readthedocs.io/en/latest/) and make a plugin out of it. But there won't be a conflict if the above case also happen.

**Comment by akbargumbira** [comment]
I just plug directory parameters (in https://github.com/akbargumbira/parameters/tree/setup_file) in inasafe and it works fine. So we don't really need to change the importing external libraries in safe (but having it consistent is nice though). 

The problem is that, we can't use submodules as it will clone from the top level (it will be safe_extras.parameters.parameters). With this problem, I do think that we should make it consistent as well ('it' being how we put all the external libraries. Now parameters use submodules but not the others). What about having a script to download all the safe_extras for development and release e.g:
```
pip install git+https://github.com/akbargumbira/parameters.git@setup_file -t /path/to/inasafe/safe_extras
```
Same applies with the other 3 libraries (I think it's better than copying it directly). Unless we modify something there directly (do we?)

**Comment by Gustry** [comment]
This PR is ok for me if you need it for your work! Thanks

**Pull request merged**
